import eslintPluginAstro from 'eslint-plugin-astro';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    // public/cdn/v1/ and public/scripts/ are generated by scripts/build-cdn.mjs
    // (vendored agentlet-core and pdf.js, plus this project's own bundled
    // esbuild output) and gitignored; they are not authored source.
    ignores: [
      'dist/',
      '.astro/',
      '.wrangler/',
      'node_modules/',
      'public/cdn/v1/',
      'public/scripts/',
      'test-results/',
      'playwright-report/',
    ],
  },
  ...tseslint.configs.recommended,
  ...eslintPluginAstro.configs.recommended,
  {
    rules: {
      'no-console': 'off',
    },
  },
);
