import eslintPluginAstro from 'eslint-plugin-astro';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    // public/cdn/v1/ is generated by scripts/build-cdn.mjs (vendored
    // agentlet-core and pdf.js, plus this project's own bundled esbuild
    // output) and gitignored; it is not authored source.
    ignores: [
      'dist/',
      '.astro/',
      '.wrangler/',
      'node_modules/',
      'public/cdn/v1/',
      // Built contents of the @agentlet/demos npm package, see
      // scripts/build-known-sites.mjs.
      'packages/agentlet-demos/dist/',
      'test-results/',
      'playwright-report/',
    ],
  },
  ...tseslint.configs.recommended,
  ...eslintPluginAstro.configs.recommended,
  {
    rules: {
      'no-console': 'off',
    },
  },
);
