import type { AIFormExport, FormFillValue, PageHighlighterHighlightControl, PDFProcessorAPI } from 'agentlet-core';
import { AGENTLET_BASE_STYLES, resumeUrlMonitoring, sourceLinkHtml, suspendUrlMonitoring } from './shared';

/**
 * "Receipt to expense report": reads the site's own sample receipt, shows
 * what an AI would receive from the sandbox form (src/components/landing/
 * TrySandbox.astro), fills that form with a recorded response, and
 * highlights what changed. Never submits the form.
 *
 * Home page only: the sandbox this agentlet operates on only exists on
 * `/`. checkPattern() only gates automatic URL-based activation (see
 * agentlet-core's ModuleRegistry.findMatchingModule()), not a manual "Try
 * it" click from the launcher (src/agentlets/launcher.ts), which activates
 * a module directly. _render() below defends against that gap by checking
 * for the sandbox form itself and showing a clear message instead of
 * failing silently if it is missing (e.g. this agentlet launched from a
 * docs page).
 */
const HOME_PAGE_PATTERN = '^https?:\\/\\/[^/]+\\/?(?:[?#].*)?$';

const FILE = 'expense-receipt';
const RECEIPT_PDF_URL = '/demo/receipt.pdf';
const FORM_SELECTOR = '#expense-form';
const DEMO_SECTION_URL = '/#demo';

/**
 * Must match src/scripts/demo-loader.ts's own `PDF_WORKER_URL` (not
 * exported from there, so duplicated here; see the comment on
 * `_ensurePdfWorker()` below for why this module also needs it directly).
 */
const PDF_WORKER_URL = '/cdn/v1/pdf.worker.min.mjs';

/**
 * Recorded response for the one receipt this agentlet supports (public/demo/
 * receipt.pdf, generated by scripts/generate-demo-receipt.mjs). Keep these
 * values in sync with that script by hand: there is no shared runtime
 * import between a Node build script and this browser bundle. Vendor
 * Riverside Bistro, dated 14 Mar 2026, subtotal 66.00, VAT (20%) 13.20,
 * total 79.20 GBP, category "Meals and entertainment".
 *
 * Keys match the sandbox form fields' `name` attributes: FormFiller.
 * fillFromAIData() (agentlet-core's src/utils/data-processing/FormFiller.ts)
 * looks up each exported element by `userValues[element.name] ||
 * userValues[element.id]`, and every sandbox field is named after its
 * purpose (see TrySandbox.astro).
 */
const RECORDED_AI_RESPONSE: Record<string, FormFillValue> = {
	vendor: 'Riverside Bistro',
	date: '2026-03-14',
	amount: '79.20',
	vatAmount: '13.20',
	currency: 'GBP',
	category: 'meals',
};

type StepId = 'read' | 'inspect' | 'fill' | 'done';

const STEP_ORDER: StepId[] = ['read', 'inspect', 'fill', 'done'];

const STEP_LABELS: Record<StepId, string> = {
	read: 'Read the receipt',
	inspect: 'See what the AI receives',
	fill: 'Fill the form',
	done: 'Done',
};

const STYLES = `
.expense-intro {
	color: var(--color-text-muted, #5b6b78);
	font-size: 0.9rem;
}

.expense-steps {
	list-style: none;
	margin: 0;
	padding: 0;
	display: flex;
	flex-direction: column;
	gap: 4px;
	font-size: 0.85rem;
}

.expense-steps li {
	display: flex;
	align-items: center;
	gap: 8px;
	padding: 4px 0;
	color: var(--color-text-muted, #5b6b78);
}

.expense-steps li.is-current {
	color: var(--color-heading, #0f3350);
	font-weight: 600;
}

.expense-steps li.is-done {
	color: var(--color-text, #3d4f5e);
}

.expense-step-marker {
	display: inline-flex;
	align-items: center;
	justify-content: center;
	width: 18px;
	height: 18px;
	border-radius: 999px;
	border: 1.5px solid currentColor;
	font-size: 0.7rem;
	flex-shrink: 0;
}

.expense-output {
	border: 1px solid var(--color-surface-border, #d9e0e6);
	border-radius: 10px;
	padding: 12px;
	background: var(--color-surface, #f4f6f8);
	display: flex;
	flex-direction: column;
	gap: 10px;
}

.expense-thumb {
	display: block;
	max-width: 100%;
	border: 1px solid var(--color-surface-border, #d9e0e6);
	border-radius: 6px;
}

.expense-note {
	margin: 0;
	font-size: 0.82rem;
	color: var(--color-text-muted, #5b6b78);
}

.expense-recorded-label {
	display: inline-block;
	font-family: 'IBM Plex Mono', ui-monospace, monospace;
	font-size: 0.7rem;
	text-transform: uppercase;
	letter-spacing: 0.04em;
	padding: 2px 8px;
	border-radius: 999px;
	background: var(--color-badge-bg, #fde8d7);
	color: var(--color-badge-text, #7a3a10);
	margin-bottom: 6px;
}

.expense-json {
	margin: 0;
	font-family: 'IBM Plex Mono', ui-monospace, monospace;
	font-size: 0.78rem;
	white-space: pre-wrap;
	word-break: break-word;
	max-height: 220px;
	overflow-y: auto;
}

.expense-details summary {
	cursor: pointer;
	font-weight: 600;
	color: var(--color-heading, #0f3350);
	font-size: 0.9rem;
}

.expense-error {
	border: 1px solid #c0392b;
	background: rgba(192, 57, 43, 0.08);
	color: #c0392b;
	border-radius: 8px;
	padding: 10px 12px;
	font-size: 0.85rem;
}

.expense-actions {
	display: flex;
	align-items: center;
	gap: 12px;
	flex-wrap: wrap;
}

.expense-restart {
	appearance: none;
	background: none;
	border: none;
	padding: 0;
	font: inherit;
	font-size: 0.85rem;
	font-weight: 600;
	color: var(--color-heading, #0f3350);
	text-decoration: underline;
	text-decoration-color: var(--color-accent, #f4a261);
	text-decoration-thickness: 2px;
	text-underline-offset: 3px;
	cursor: pointer;
}

.expense-actions button:disabled {
	opacity: 0.6;
	cursor: not-allowed;
}
`;

class ExpenseReceiptModule extends window.agentlet.Module {
	private _step: StepId = 'read';
	private _busy = false;
	private _error: string | null = null;
	private _receiptImage: string | null = null;
	private _aiExport: AIFormExport | null = null;
	/** True from the moment "Fill the form" is clicked (see _handleFill()); gates the "Recorded AI response" block so it appears with the fill itself, not merely once the button is available (review round 1). */
	private _filled = false;
	private _highlights: PageHighlighterHighlightControl[] = [];
	/** Pending closing-bubble timer (see _handleFill()); cleared on unmount/restart so a stale bubble cannot appear after the panel moves on. */
	private _closingBubbleTimeout: ReturnType<typeof setTimeout> | null = null;
	private _container: HTMLElement | null = null;

	constructor() {
		super({
			name: 'expense-receipt',
			description: 'Reads a receipt and fills an expense report form for you to review.',
			patterns: [{ type: 'regex', value: HOME_PAGE_PATTERN }],
		});
	}

	getPanelTitle(): string {
		return 'Receipt to expense report';
	}

	async mount(container: HTMLElement): Promise<void> {
		this.injectStyles(AGENTLET_BASE_STYLES + STYLES);
		this._container = container;
		this._renderInto(container);
	}

	async unmount(): Promise<void> {
		this._clearHighlights();
		this._clearClosingBubbleTimeout();
		this._container = null;
	}

	/** See shared.ts's ModuleRegistryUrlMonitoring comment: suspends the core's URL-change polling for as long as this agentlet stays active. */
	async activateModule(): Promise<void> {
		suspendUrlMonitoring();
	}

	async cleanupModule(): Promise<void> {
		this._clearHighlights();
		resumeUrlMonitoring();
	}

	private _formElement(): HTMLFormElement | null {
		return document.querySelector<HTMLFormElement>(FORM_SELECTOR);
	}

	private _clearHighlights(): void {
		this._highlights.forEach((highlight) => highlight.destroy());
		this._highlights = [];
	}

	private _clearClosingBubbleTimeout(): void {
		if (this._closingBubbleTimeout !== null) {
			clearTimeout(this._closingBubbleTimeout);
			this._closingBubbleTimeout = null;
		}
	}

	private _renderInto(container: HTMLElement): void {
		container.innerHTML = this._render();
		this._wireActions(container);
	}

	private _rerender(): void {
		if (this._container) this._renderInto(this._container);
	}

	private _render(): string {
		if (!this._formElement()) {
			return `
				<div class="agentlet-panel-body">
					<h3>Receipt to expense report</h3>
					<p class="expense-intro">
						This demo works on agentlet.io's home page, where the sample receipt and the expense
						form live. Go to the home page and open this demo again from there.
					</p>
					${sourceLinkHtml(FILE)}
				</div>
			`;
		}

		return `
			<div class="agentlet-panel-body">
				<h3>Receipt to expense report</h3>
				<p class="expense-intro">
					Reads the sample receipt below, shows what an AI would receive from the form, fills it
					with a recorded response, then highlights what changed for you to review.
				</p>

				${this._renderSteps()}
				${this._error ? `<p class="expense-error">${this._escape(this._error)}</p>` : ''}
				${this._renderOutput()}
				${this._renderActions()}

				${sourceLinkHtml(FILE)}
			</div>
		`;
	}

	private _renderSteps(): string {
		const currentIndex = STEP_ORDER.indexOf(this._step);
		const items = STEP_ORDER.filter((id) => id !== 'done')
			.map((id, index) => {
				const state = index < currentIndex ? 'is-done' : index === currentIndex ? 'is-current' : '';
				const marker = index < currentIndex ? '&#10003;' : String(index + 1);
				return `<li class="${state}"><span class="expense-step-marker">${marker}</span>${STEP_LABELS[id]}</li>`;
			})
			.join('');
		return `<ol class="expense-steps">${items}</ol>`;
	}

	private _renderOutput(): string {
		const blocks: string[] = [];

		if (this._receiptImage) {
			blocks.push(
				`<img class="expense-thumb" src="${this._receiptImage}" alt="Thumbnail of the sample receipt, page 1" width="220" />`,
			);
			// Shown for as long as the thumbnail stays visible (every step
			// from here on): only this one receipt is supported, on purpose,
			// and the AI response shown later is recorded for it, not live.
			blocks.push(
				'<p class="expense-note">Only this sample receipt is supported: the answer below is recorded for it, not generated by a live AI.</p>',
			);
		}

		if (this._aiExport) {
			// Expanded by default (review round 1: a collapsed block showed
			// nothing new when this step revealed it), but still a real
			// <details> the visitor can collapse by hand.
			blocks.push(`
				<details class="expense-details" open>
					<summary>Form data sent to the AI</summary>
					<pre class="expense-json">${this._escape(JSON.stringify(this._aiExport, null, 2))}</pre>
				</details>
			`);
		}

		if (this._filled) {
			blocks.push(`
				<div>
					<span class="expense-recorded-label">Recorded AI response</span>
					<pre class="expense-json">${this._escape(JSON.stringify(RECORDED_AI_RESPONSE, null, 2))}</pre>
				</div>
			`);
		}

		if (this._step === 'done') {
			blocks.push(
				'<p class="expense-note">The form was filled and the changed fields are highlighted on the page. Review it, then submit it by hand if you want; this agentlet never submits it for you.</p>',
			);
		}

		if (blocks.length === 0) return '';
		return `<div class="expense-output">${blocks.join('')}</div>`;
	}

	private _renderActions(): string {
		const restartButton =
			this._step !== 'read' || this._receiptImage
				? '<button type="button" class="expense-restart" data-action="restart">Start over</button>'
				: '';

		if (this._step === 'done') {
			return `<div class="expense-actions">${restartButton}</div>`;
		}

		const label = this._busy ? 'Working...' : STEP_LABELS[this._step];
		return `
			<div class="expense-actions">
				<button type="button" class="agentlet-try-button" data-action="primary" ${this._busy ? 'disabled' : ''}>${label}</button>
				${restartButton}
			</div>
		`;
	}

	private _escape(value: string): string {
		return value
			.replace(/&/g, '&amp;')
			.replace(/</g, '&lt;')
			.replace(/>/g, '&gt;');
	}

	private _wireActions(container: HTMLElement): void {
		container.querySelector('[data-action="primary"]')?.addEventListener('click', () => {
			void this._runStep();
		});
		container.querySelector('[data-action="restart"]')?.addEventListener('click', () => {
			this._restart();
		});
	}

	private async _runStep(): Promise<void> {
		this._busy = true;
		this._error = null;
		this._rerender();

		try {
			if (this._step === 'read') {
				await this._handleRead();
				this._step = 'inspect';
			} else if (this._step === 'inspect') {
				await this._handleInspect();
				this._step = 'fill';
			} else if (this._step === 'fill') {
				await this._handleFill();
				this._step = 'done';
			}
		} catch (error) {
			this._error = error instanceof Error ? error.message : String(error);
			window.agentlet?.utils.MessageBubble.error(this._error);
		} finally {
			this._busy = false;
			this._rerender();
		}
	}

	/**
	 * Second core bug worked around here: `LibrarySetup.setupPDFJS()`
	 * (agentlet-core src/libraries/LibrarySetup.ts) only configures
	 * `pdfjsLib.GlobalWorkerOptions.workerSrc` from `config.pdfWorkerUrl`
	 * inside a guard, `if (typeof globals.pdfjsLib === 'undefined')`. In
	 * this build, `window.pdfjsLib` is already defined by the time that
	 * runs (`window.agentlet.config.pdfWorkerUrl` correctly holds
	 * `/cdn/v1/pdf.worker.min.mjs` the whole time, confirmed at runtime),
	 * so the guard is false and the worker URL is never applied: the very
	 * first PDF conversion fails with pdf.js's own `No
	 * "GlobalWorkerOptions.workerSrc" specified.` error. PDFProcessor's own
	 * catch block then "helpfully" retries once against a hardcoded
	 * `cdnjs.cloudflare.com` worker URL, which this site's CSP (`script-src
	 * 'self' ...`, no `cdnjs.cloudflare.com`) blocks outright, so even the
	 * automatic fallback cannot succeed here. Worked around by calling the
	 * real, public `window.agentlet.configurePDFWorker()` (part of the
	 * shipped `AgentletAPI`) ourselves, once pdf.js is confirmed loaded, so
	 * the worker URL is set correctly before the first conversion ever
	 * runs. See the build report for the exact repro to file against
	 * agentlet-core.
	 */
	private async _ensurePdfWorker(processor: PDFProcessorAPI): Promise<void> {
		const available = await processor.ensurePDFJS();
		if (!available) throw new Error('PDF.js could not be loaded in this browser.');
		window.agentlet?.configurePDFWorker(PDF_WORKER_URL);
	}

	/** Step 1: fetch the sample receipt (same origin) and convert it to a thumbnail image. */
	private async _handleRead(): Promise<void> {
		const processor = window.agentlet?.utils.PDFProcessor;
		if (!processor) throw new Error('The PDF processor is not available in this browser.');

		await this._ensurePdfWorker(processor);

		const images = await processor.convertPDFFromURL(RECEIPT_PDF_URL, { scale: 1.5 });
		if (images.length === 0) throw new Error('The sample receipt could not be converted to an image.');
		this._receiptImage = images[0];
	}

	/** Step 2: show the sandbox form structure the way an AI would receive it. */
	private async _handleInspect(): Promise<void> {
		const form = this._formElement();
		if (!form) throw new Error('The expense form could not be found on this page.');

		const forms = window.agentlet?.forms;
		if (!forms) throw new Error('The forms API is not available in this browser.');

		this._aiExport = forms.exportForAI(form);
	}

	/** Steps 3-5: apply the recorded response, highlight what changed, scroll it into view, then hand off. */
	private async _handleFill(): Promise<void> {
		// Marks the "Recorded AI response" block visible from the moment this
		// action starts, not merely once the "Fill the form" button became
		// available (review round 1: showing it earlier revealed two things
		// at once when step 2 completed).
		this._filled = true;

		const form = this._formElement();
		if (!form) throw new Error('The expense form could not be found on this page.');

		const forms = window.agentlet?.forms;
		if (!forms) throw new Error('The forms API is not available in this browser.');
		if (!this._aiExport) this._aiExport = forms.exportForAI(form);

		const result = forms.fillFromAI(form, this._aiExport, RECORDED_AI_RESPONSE, { triggerEvents: true });
		if (result.successful === 0) {
			throw new Error('None of the recorded values could be applied to the form.');
		}

		this._clearHighlights();
		const highlighter = window.agentlet?.utils.PageHighlighter;
		// Border only, no per-field tooltip (review round 1: six "Filled by
		// the agentlet" messages covered the field labels next to them). The
		// one message the visitor gets is on the Submit button instead, below.
		for (const detail of result.details) {
			if (detail.status !== 'success') continue;
			const element = document.querySelector(detail.selector);
			if (!element || !highlighter) continue;
			const highlight = highlighter.highlight(element, {
				type: 'border',
				style: 'success',
				animation: 'pulse',
			});
			if (highlight) this._highlights.push(highlight);
		}

		const submitButton = form.querySelector('button[type="submit"]');
		if (submitButton && highlighter) {
			const submitHighlight = highlighter.highlight(submitButton, {
				type: 'border',
				style: 'warning',
				animation: 'pulse',
				message: 'Check before submitting',
			});
			if (submitHighlight) this._highlights.push(submitHighlight);
		}

		// Scrolls the form into view: the visitor is looking at the panel
		// (and, behind it, the hero) when they click "Fill the form", so the
		// sandbox section further down the page is off-screen otherwise
		// (review round 1).
		if (highlighter) {
			await highlighter.scrollTo(form, { behavior: 'smooth', block: 'center' });
		}

		window.agentlet?.utils.MessageBubble.info('Check before submitting.', { duration: 8000, closable: true });

		// Delayed so this bubble does not stack with the one right above
		// (review round 1: both used to appear at the same instant).
		this._closingBubbleTimeout = setTimeout(() => {
			this._closingBubbleTimeout = null;
			window.agentlet?.utils.MessageBubble.show({
				type: 'info',
				message: `This ran on agentlet.io. <a href="${DEMO_SECTION_URL}" style="color: inherit;">See it on a real business app</a>.`,
				allowHtml: true,
				duration: 0,
				closable: true,
			});
		}, 2000);
	}

	private _restart(): void {
		this._formElement()?.reset();
		this._clearHighlights();
		this._clearClosingBubbleTimeout();
		window.agentlet?.utils.MessageBubble.hideAll();
		this._step = 'read';
		this._busy = false;
		this._error = null;
		this._receiptImage = null;
		this._aiExport = null;
		this._filled = false;
		this._rerender();
	}
}

(window as unknown as Record<string, unknown>).ExpenseReceiptModule = ExpenseReceiptModule;
